spring.application.name=BLCMWEB
server.port=80


spring.datasource.url=jdbc:oracle:thin:@iiqsegundabase_medium?TNS_ADMIN=./src/main/resources/wallet

spring.datasource.username=BLCMWEB
spring.datasource.password=Fidelitas$2026

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false

logging.level.org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.security=DEBUG
spring.thymeleaf.cache=false

logging.level.org.springframework.security=DEBUG
